version: "3.4"

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    expose:
      - "3307"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "soscretthatnearlycannotbefindout"
      MYSQL_DATABASE: "go_image_uploader"
      MYSQL_PASSWORD: "soscretthatnearlycannotbefindout"
    ports:
      - "3308:3306"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "8085:80"
    expose:
      - 8081
  imageuploadserver:
    image: imageuploadserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mysql
    links:
      - mysql
